### PR TITLE
bug fix: add SIGKILL signal

### PR DESCRIPTION
**Pull request by zeusro**
It may slove https://github.com/alibaba/kt-connect/issues/96

### CODE REVIEW

**Comment by yunlzheng** [comment]
@zeusro ktctl is a executable file not running in container.

**Comment by zeusro** [comment]
> @zeusro ktctl is a executable file not running in container.

Ohhhh,I copied that code from other codebase without caring about the comment. 

Not just the container，the `SIGKILL ` signal is also used  in the MAC/Linux system

>   https://en.wikipedia.org/wiki/Signal_(IPC) 
> SIGKILL is used as a last resort when terminating processes in most system shutdown procedures if it does not voluntarily exit in response to SIGTERM. To speed the computer shutdown procedure, Mac OS X 10.6, aka Snow Leopard, will send SIGKILL to applications that have marked themselves "clean" resulting in faster shutdown times with, presumably, no ill effects.
>

**Comment by zeusro** [comment]
https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html

**Comment by yunlzheng** [comment]
Cool! 

> > @zeusro ktctl is a executable file not running in container.
> 
> Ohhhh,I copied that code from other codebase without caring about the comment.
> 
> Not just the container，the `SIGKILL ` signal is also used in the MAC/Linux system
> 
> > https://en.wikipedia.org/wiki/Signal_(IPC)
> > SIGKILL is used as a last resort when terminating processes in most system shutdown procedures if it does not voluntarily exit in response to SIGTERM. To speed the computer shutdown procedure, Mac OS X 10.6, aka Snow Leopard, will send SIGKILL to applications that have marked themselves "clean" resulting in faster shutdown times with, presumably, no ill effects.

**Pull request merged**
